# Generated by Django 3.2 on 2021-05-18 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_auto_20210518_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='School',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='newapp.school'),
        ),
    ]
